# code: language=ansible
---
- name: "Customizing Kali"
  hosts: core
  become: true
  roles:
    # - role: "roles/pre-config"
    # - role: "roles/package-install"
    - role: "roles/tools-install"
      vars:
      - optional_tools: 
        # - "sublime"
        - "vscode"
    - role: "roles/system-customizations"
