# code: language=ansible
---
- name: Add an Apt signing key for Sublime Text repo
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes

- name: Add Sublime Text repository 
  ansible.builtin.apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublime-text
  become: yes

- name: Update repositories cache and install Sublime Text
  ansible.builtin.apt:
    name: sublime-text
    update_cache: yes
  become: yes